#!/bin/sh

BASE_PATH=$PROJECT_DIR/$PROJECT_NAME

echo execute copy GoogleService-Info.plist
FIREBASE_INFO_PLIST="GoogleService-Info.plist"
FIREBASE_INFO_PLIST_DST=$BASE_PATH/$FIREBASE_INFO_PLIST
FIREBASE_INFO_PLIST_SRC=$FIREBASE_DIR/$FIREBASE_INFO_PLIST

echo $FIREBASE_INFO_PLIST_SRC
cp -Rf $FIREBASE_INFO_PLIST_SRC $FIREBASE_INFO_PLIST_DST
