include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "lib/l10n/messages_*.dart"
    - "lib/data/model/*.g.dart"
    - "lib/data/model/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    prefer_const_constructors: true
    # IDE works bad with relative import
    # See: https://github.com/dart-lang/sdk/issues/32916
    prefer_relative_imports: false
    always_use_package_imports: true
