include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/generated_plugin_registrant.dart"
    - "**/build/**"
    - "**/generated_*.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/l10n*.dart"
    - "**/*.gen.dart"